dist: xenial
language: python
stages:
  - syntax
  - test
jobs:
  include:
    - stage: syntax
      python: "3.6"
      install:
        - pip install -r requirements.txt flake8 black
      script:
        - flake8
        - black --check --diff .
    - stage: test
      python: "3.4"
      install:
        - pip install -r requirements.txt tox-travis
      script:
        - python setup.py test
    - stage: test
      python: "3.5"
      install:
        - pip install -r requirements.txt tox-travis
      script:
        - tox
    - stage: test
      python: "3.6"
      install:
        - pip install -r requirements.txt tox-travis
      script:
        - python setup.py test
    - stage: test
      python: "3.7"
      install:
        - pip install -r requirements.txt tox-travis
      script:
        - python setup.py test
